//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string EmptyStringsAfterAndBeforeBracesAnalyzerDescription {
            get {
                return ResourceManager.GetString("EmptyStringsAfterAndBeforeBracesAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can be removed.
        /// </summary>
        public static string EmptyStringsAfterAndBeforeBracesAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("EmptyStringsAfterAndBeforeBracesAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String can be removed..
        /// </summary>
        public static string EmptyStringsAfterAndBeforeBracesAnalyzerTitle {
            get {
                return ResourceManager.GetString("EmptyStringsAfterAndBeforeBracesAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string EmptyStringsInOrderAnalyzerDescription {
            get {
                return ResourceManager.GetString("EmptyStringsInOrderAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can be removed.
        /// </summary>
        public static string EmptyStringsInOrderAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("EmptyStringsInOrderAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String can be removed..
        /// </summary>
        public static string EmptyStringsInOrderAnalyzerTitle {
            get {
                return ResourceManager.GetString("EmptyStringsInOrderAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string WhitespacesStringsAnalyzerDescription {
            get {
                return ResourceManager.GetString("WhitespacesStringsAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can be removed.
        /// </summary>
        public static string WhitespacesStringsAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("WhitespacesStringsAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whitespaces can be removed..
        /// </summary>
        public static string WhitespacesStringsAnalyzerTitle {
            get {
                return ResourceManager.GetString("WhitespacesStringsAnalyzerTitle", resourceCulture);
            }
        }
    }
}
